modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/lukebemish/revamped_phantoms/issues"
license = "LGPL v3"

[[mods]]
modId = "revamped_phantoms"
version = "${version}"
displayName = "Revamped Phantoms"
authors = "Luke Bemish"
description = '''
Description here
'''
# logoFile = "icon.png"

[[dependencies.revamped_phantoms]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.revamped_phantoms]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.revamped_phantoms]]
modId = "architectury"
mandatory = true
versionRange = "[3.3.7,)"
ordering = "AFTER"
side = "BOTH"